from geopy.distance import vincenty
from geopy.geocoders import GoogleV3

dict = {"Washington Redskins":"Landover, MD",
"New York Jets":"East Rutherford, NJ",
"New York Giants":"East Rutherford, NJ",
"Green Bay Packers":"Green Bay, WI",
"Dallas Cowboys":"Arlington, TX",
"Kansas City Chiefs":"Kansas City, MO",
"Denver Broncos":"Denver, CO",
"Miami Dolphins":"Miami Gardens, FL",
"Carolina Panthers":"Charlotte, NC",
"New Orleans Saints":"New Orleans, LA",
"Cleveland Browns":"Cleveland, OH",
"Buffalo Bills":"Orchard Park, NY",
"Atlanta Falcons":"Atlanta, GA",
"Houston Texans":"Houston, TX",
"Baltimore Ravens":"Baltimore, MD",
"San Diego Chargers":"San Diego, CA",
"Tennessee Titans":"Nashville, TN",
"New England Patriots":"Foxboro, MA",
"Philadelphia Eagles":"Philadelphia, PA",
"San Francisco 49ers":"Santa Clara, CA",
"Jacksonville Jaguars":"Jacksonville, FL",
"Seattle Seahawks":"Seattle, WA",
"St Louis Rams":"St. Louis, MO",
"Tampa Bay Buccaneers":"Tampa, FL",
"Cincinnati Bengals":"Cincinnati, OH",
"Pittsburgh Steelers":"Pittsburgh, PA",
"Detroit Lions":"Detroit, MI",
"Arizona Cardinals":"Glendale, AZ",
"Indianapolis Colts":"Indianapolis, IN",
"Chicago Bears":"Chicago, IL",
"Oakland Raiders":"Oakland, CA",
"Minnesota Vikings":"Minneapolis, MN",
"Baltimore Colts": "Baltimore, MD",
"Tennessee Oilers": "Nashville, TN",
"Houston Oilers": "Houston, TX",
"Los Angeles Rams": "Los Angeles, CA",
"Los Angeles Raiders": "Los Angeles, CA",
"St Louis Cardinals": "St. Louis, MO",
"Phoenix Cardinals": "Tempe, AZ"}

dict2 = {'Blackpool': 'Blackpool',
'Liverpool': 'Liverpool',
'West Ham': 'London',
'Oldham Athletic':	'Oldham',
'Sheffield United':	'Sheffield',
'Stoke':	'Stoke-on-Trent',
'Cardiff':	'Cardiff',
'Norwich':	'Norwich',
'Nottingham Forest':	'Nottingham',
'Man City':	'Manchester',
'Swindon Town':	'Swindon',
'Fulham':	'London',
'Wigan':	'Wigan',
'Leeds':	'Leeds',
'Arsenal':	'London',
'Coventry':'Coventry',
'Blackburn':	'Blackburn',
'Portsmouth':	'Portsmouth',
'Everton':	'Liverpool',
'West Brom':	'West Bromwich',
'Sheffield Wednesday':	'Sheffield',
'Hull': 'Kingston upon Hull',
'Leicester':	'Leicester',
'Swansea':	'Swansea',
'QPR': 'London',
'Fulham': 'London',
'Reading':	'Reading, UK',
'Wolves':	'Wolverhampton',
'Barnsley':	'Barnsley',
'Man United': 'Manchester',
'Ipswich':	'Ipswich',
'Derby':	'Derby',
'Bolton':	'Bolton',
'Middlesbrough':	'Middlesbrough',
'Birmingham':	'Birmingham, UK',
'Newcastle':	'Newcastle',
'Southampton':	'Southampton',
'Crystal Palace':	'London',
'Sunderland':	'Sunderland',
'Chelsea':	'London',
'Burnley':	'Burnley',
'Charlton':	'London',
'Bradford':	'Bradford',
'Watford':	'Watford',
'Aston Villa':	'Birmingham',
'Tottenham':	'London'}

geolocator = GoogleV3()
def travel(teamA, teamB):
	locA, (latA, longA) = geolocator.geocode(dict2[teamA])
	locB, (latB, longB) = geolocator.geocode(dict2[teamB])
	coordA = (latA, longA)
	coordB = (latB, longB)
	return vincenty(coordA, coordB).miles
print travel("Birmingham", "Reading")